Topic 50 | Why NumPy & Environment Setup
This topic explains why NumPy is more efficient than pure Python lists. It covers ndarrays, shapes, dtypes, and basic environment setup for numerical computing.

In [51]:
import numpy as np
import time

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)  # Output: [[1 2 3]
print(arr.shape)    # find a rows and columns
print(arr.ndim)   # find a dimension
print(arr.dtype)   # find a data type
print(arr.size)    # find a total number of elements

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64
6

In [53]:
py_list = list(range(1_000_000))
py_result = []
start_time = time.time()
for i in py_list:
    py_result.append(i+5)
end_time = time.time()
print("Python list time:", end_time - start_time)

Python list time: 0.1310744285583496

In [54]:
np_arr = np.arange(1_000_000)
start_time = time.time()
np_result = np_arr + 5
end_time = time.time()
print("NumPy array time:", end_time - start_time)

NumPy array time: 0.005011320114135742

Topic 51 | Creating Arrays in NumPy
This topic covers creating arrays using lists, zeros, ones, arange, linspace, and other functions. It also explains building multi dimensional arrays and converting between data types.

In [55]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]

In [56]:
print(np.zeros((2,3)))   # 2 rows and 3 columns of zeros
print(np.ones((2,3)))    # 2 rows and 3 columns of ones

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]

In [57]:
print(np.full((2,3),7))   # 2 rows and 3 columns of sevens

[[7 7 7]
 [7 7 7]]

In [58]:
print(np.arange(0, 10, 2))   # start at 0, end before 10, step by 2

[0 2 4 6 8]

In [59]:
print(np.linspace(0, 1, 5)) # start at 0, end at 1, 5 evenly spaced numbers

[0.   0.25 0.5  0.75 1.  ]

In [60]:
print(np.eye(3)) # 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [61]:
print(np.diag([1, 2, 3])) # 3x3 diagonal matrix with 1, 2, 3 on the diagonal

[[1 0 0]
 [0 2 0]
 [0 0 3]]

In [62]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [63]:
arr = np.array([1.5, 2.7, 3.5])
print(arr.astype(int))  # Convert to integers (truncates decimals)

[1 2 3]

Topic 52 | NumPy Indexing, Slicing & Strides
This topic explains how to index and slice arrays using steps, negative indices, and multidimensional selections. It highlights the difference between views and copies through practical examples.

In [64]:
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [65]:
print(arr[0, 1])  # Access element at row 0, column 1a
print(arr[2, 2]) # Access element at row 2, column 2

20
90

In [66]:
print(arr[-1, -2]) # Access element at last row, second last column
print(arr[-3, -3]) # Access element at first row, last column

80
10

In [67]:
print(arr[0:2, 1:3]) # Access a subarray from row 0 to 1 and column 1 to 2

[[20 30]
 [50 60]]

In [68]:
print(arr[::2, ::2]) # Access every second row and every second column

[[10 30]
 [70 90]]

In [69]:
slice_arr = arr[0:2, 1:3]  # Create a slice of the array
print(slice_arr)

[[20 30]
 [50 60]]

In [70]:
slice_arr =arr[0, :2]
slice_arr[0] = 999  # Modify the first element of the slice
print(arr)  # The original array is also modified

[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]

In [71]:
copy_arr = arr[1].copy()  # Create a copy of the second row
copy_arr[0] = 888  # Modify the first element of the copy
print(arr[1])  # The original array remains unchanged

[40 50 60]

Topic 53 | NumPy Random Numbers, Reproducibility & Performance Tips
This topic highlights how to generate random numbers using NumPy’s Generator and apply seeding for reproducibility. It also compares vectorized operations with loops and includes a coin flip simulation.

In [72]:
import numpy as np
rng = np.random.default_rng() # Create a random number generator
flips = rng.integers(0, 2, size=100000) # Generate 100,000 random integers (0 or 1)  0 = tails, 1 = heads
prob_heads = np.mean(flips) # Calculate the proportion of heads (1s)
print("Estimated Probability of Heads:", prob_heads) # Output: Approximately 0.5 (varies with each run)

Estimated Probability of Heads: 0.50093

In [73]:
import numpy as np
rng = np.random.default_rng(seed=43) # Create a random number generator with a fixed seed for reproducibility
flips = rng.integers(0, 2, size=100000) # Generate 100,000 random integers (0 or 1)  0 = tails, 1 = heads
prob_heads = np.mean(flips) # Calculate the proportion of heads (1s)
print("Estimated Probability of Heads:", prob_heads) # Output: Approximately 0.5 (varies with each run)

Estimated Probability of Heads: 0.50238

In [74]:
import time

start_time = time.time()
squares = [i**2 for i in range(1000000)]
end_time = time.time()
print("loop time:", end_time - start_time)

#numpy vectorized
start_time = time.time()
arr = np.arange(1000000)
squares = arr ** 2
end_time = time.time()
print("vectorized time:", end_time - start_time)

loop time: 0.11654448509216309
vectorized time: 0.02052021026611328

Topic 54 | Pandas Series - Fundamentals
This topic explains how to create and inspect Pandas Series, focusing on indexes, values, and inferred data types. It also covers essential methods like .head(), .tail(), and .value_counts().

In [75]:
import pandas as pd

In [76]:
s = pd.Series([10, 20, 20, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print(s)

a    10
b    20
c    20
d    40
e    50
dtype: int64

In [77]:
print("Values:", s.values)
print("Index:", s.index)
print("Data type:", s.dtype)

Values: [10 20 20 40 50]
Index: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Data type: int64

In [78]:
print(s.head)

<bound method NDFrame.head of a    10
b    20
c    20
d    40
e    50
dtype: int64>

In [79]:
print(s.tail)

<bound method NDFrame.tail of a    10
b    20
c    20
d    40
e    50
dtype: int64>

In [80]:
print(s.value_counts())

20    2
10    1
40    1
50    1
Name: count, dtype: int64

Topic 55 | Pandas DataFrames - Creation & Inspection
This topic covers building DataFrames and loading CSV files. It highlights dataset inspection using .info(), .describe(), .dtypes, and .shape.

In [81]:
import pandas as pd
data = {'Name':['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age':[25, 30, 22, 35, 28],
        'City':['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago
3    David   35      Houston
4      Eva   28      Phoenix

In [82]:
df = pd.read_csv('retail_sales.csv')
print("info\n", df.info())  # Print information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1826 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB
info
 None

In [83]:
print(df.shape)  # Print the shape of the DataFrame (rows, columns)
print(df.dtypes)  # Print the data types of each column

(1826, 6)
Date         object
Category     object
Sales       float64
Quantity    float64
Profit      float64
Region       object
dtype: object

In [84]:
print(df.describe())  # Print summary statistics of the DataFrame

             Sales     Quantity       Profit
count  1823.000000  1820.000000  1825.000000
mean    980.482677    10.053846   248.696130
std     336.756618     5.515370   118.159627
min       0.000000     0.000000     0.000000
25%     784.071354     5.000000   156.916498
50%     997.725134    10.000000   229.344557
75%    1208.512721    15.000000   324.867847
max    1888.932537    19.000000   703.228418

Topic 56 | Pandas Indexing & Selection - loc & iloc
This topic explains how to select data using .loc and .iloc. It covers boolean filtering and best practices for safe and clear data selection.

In [85]:
data = {'Name':['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age':[25, 30, 22, 35, 28],
        'City':['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
        'Salary':[70000, 80000, 60000, 90000, 75000]}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
       Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   35      Houston   90000
4      Eva   28      Phoenix   75000

In [86]:
# label-based indexing with loc
subset_loc = df.loc[1:3, ['Name', 'City']]  # Select rows 1 to 2 and columns 'Name' and 'City'
print("Subset using loc:\n", subset_loc)

Subset using loc:
       Name         City
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [87]:
# integer position-based indexing with iloc
subset_iloc = df.iloc[1:3, [0, 2]]  # Select rows 1 to 2 and columns at index 0 and 2
print("Subset using iloc:\n", subset_iloc)

Subset using iloc:
       Name         City
1      Bob  Los Angeles
2  Charlie      Chicago

In [88]:
# Boolean filtering
high_salary = df[df['Salary'] > 75000]  # Filter rows where Salary is greater than 75000
print("Employees with high salary:\n", high_salary)

Employees with high salary:
     Name  Age         City  Salary
1    Bob   30  Los Angeles   80000
3  David   35      Houston   90000

In [89]:
# Safe assignment using iloc
df.loc[df['Age'] < 30, 'Salary'] = 65000  # Set Salary to 65000 for employees younger than 30
print("Low age employees with updated salary:\n", df.loc[df['Age'] < 30, 'Salary'])

Low age employees with updated salary:
 0    65000
2    65000
4    65000
Name: Salary, dtype: int64

Topic 57 | Import & Export - CSV, Excel & JSON
This topic highlights how to import data using read_csv with options like parse_dates and export cleaned data to CSV, Excel, and JSON. It also touches on memory efficient loading.

In [90]:
import pandas as pd
import openpyxl

df = pd.read_csv("retail_sales.csv", parse_dates=["Date"],dtype={"Category": "category","Region": "category"})


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1826 non-null   object
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), float64(3), object(1)
memory usage: 61.3+ KB

In [91]:
clean_df = df[df["Sales"] > 0]  # Filter out rows where Sales is not greater than 0
subset_df = clean_df[["Date", "Sales", "Category", "Region"]]  # Select only the Date, Sales, and Category columns

In [92]:
import openpyxl
subset_df.to_excel("clean_retail_sales.xlsx", sheet_name="Sale")  # Save the cleaned DataFrame to an Excel file
subset_df.to_json("clean_retail_sales.json", orient="records", date_format="iso")  # Save the cleaned DataFrame to a JSON file
print("files exported successfully")
subset_df.info()  # Print information about the cleaned DataFrame

files exported successfully
<class 'pandas.core.frame.DataFrame'>
Index: 1778 entries, 0 to 1824
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1778 non-null   object
 1   Sales     1778 non-null   float64
 2   Category  1774 non-null   category
 3   Region    1775 non-null   category
dtypes: category(2), float64(1), object(1)
memory usage: 110.2+ KB

Topic 58 | Handling Data Types & Type Conversion
This topic explains how to convert data types using astype, to_datetime, to_numeric, and category types. It also compares memory usage before and after conversions.

In [93]:
import pandas as pd

df = pd.read_csv("retail_sales.csv", parse_dates=["Date"], dtype={"Category": "category"})
df.info()  # Print information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1826 non-null   object
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), float64(3), object(2)
memory usage: 73.6+ KB

In [94]:
df["Profit"] = pd.to_numeric(df["Profit"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1826 non-null   object
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), float64(3), object(2)
memory usage: 73.6+ KB

In [95]:
df['Region'] = df['Region'].astype('category')
df.info()  # Print information about the DataFrame after converting 'Region' to category
print(df['Region'].memory_usage(deep=True))  # Print memory usage of the 'Region' column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1826 non-null   object
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), float64(3), object(1)
memory usage: 61.3+ KB
2396

Topic 59 | Handling Missing Data
This topic covers detecting missing values and applying strategies such as dropna and fillna with statistical methods. It includes a practical imputation example.

In [96]:
# detect missing values in the DataFrame
print(df.isna().sum())

Date        0
Category    5
Sales       3
Quantity    6
Profit      1
Region      6
dtype: int64

In [97]:
df['Quantity'] = pd.to_numeric(df['Quantity'])# Convert 'Quantity' to numeric, setting errors to NaN
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mode()[0]) # Fill NaN values in 'Quantity' with the mode

In [98]:
df['Sales'] = df['Sales'].fillna(df['Sales'].median())  # Fill NaN values in 'Sales' with the median

In [99]:
df['Porfit'] = df['Profit'].fillna(df['Profit'].median())  # Fill NaN values in 'Profit' with the mean

In [100]:
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])  # Fill NaN values in 'Category' with the mode

In [101]:
df.dropna(subset=['Region'], inplace=True)  # Drop rows where 'Region' is NaN

In [102]:
print(df.isna().sum())

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
Porfit      0
dtype: int64

Topic 60 | String & Text Cleaning
This topic explains how to clean text using the Pandas string accessor for stripping, lowercasing, replacing, and extracting patterns. It also covers splitting and joining text fields.

In [103]:
# df = pd.DataFrame({
# 'Category': ['Electronics ', 'furniture', 'Home-Appliances', ' electronics', 'FURNITURE ']
# })

# print(df)

In [104]:
# df['Category_Clean'] = df['Category'].str.strip().str.lower()  # Remove leading/trailing whitespace and convert to lowercase
# print(df)

In [105]:
# df['Category_Clean'] =  df['Category_Clean'].str.replace('-', ' ') # Replace hyphens with spaces in 'Category_Clean'
# print(df)

Topic 61 | Sorting & Ranking Data
This topic highlights sorting data by values or index and applying ranking methods. It includes sorting by multiple columns and ranking within groups.

In [107]:
df_sorted = df.sort_values(by=['Quantity', 'Sales'], ascending=[False, True]) # Sort by 'Quantity' ascending and then by 'Sales' descending
print(df_sorted.head())

           Date    Category       Sales  Quantity      Profit Region  \
312    3/4/2023  Home Goods    0.000000      19.0    0.000000   West
528   4/16/2023      Sports    0.000000      19.0  270.577388   West
1708  12/8/2023      Sports  227.942727      19.0   61.534381  North
571   4/25/2023    Clothing  361.006937      19.0   57.285585   West
1213  8/31/2023      Sports  368.305917      19.0   73.419555   West

          Porfit
312     0.000000
528   270.577388
1708   61.534381
571    57.285585
1213   73.419555

In [109]:
df['Sales_rank'] = df.groupby('Quantity')['Sales'].rank(method='dense', ascending=False)  # Rank 'Sales' within each 'Quantity' group in descending order
print(df[['Quantity', 'Sales', 'Sales_rank']].head())  # Print the first few rows of the DataFrame with 'Quantity', 'Sales', and 'Sales_rank' columns

   Quantity        Sales  Sales_rank
0      11.0  1149.014246        29.0
1       7.0   958.520710        56.0
2       2.0  1473.763845         7.0
3       6.0  1230.230419        24.0
4      12.0   828.585950        67.0

Topic 62 | Merging & Joining DataFrames
This topic explains how to merge and join DataFrames using different join types. It also covers concatenation and handling column conflicts with suffixes.

In [2]:
import pandas as pd

In [4]:
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
})

orders = pd.DataFrame({
    'OrderID': [101, 102, 103, 104, 105],
    'CustomerID': [1, 2, 1, 3, 2],
    'Amount': [250, 150, 300, 200, 100]
})

In [5]:
df_inner = pd.merge(customers, orders, on='CustomerID', how='inner')  # Inner join on 'CustomerID'
print("Inner Join:\n", df_inner)

Inner Join:
    CustomerID     Name  OrderID  Amount
0           1    Alice      101     250
1           1    Alice      103     300
2           2      Bob      102     150
3           2      Bob      105     100
4           3  Charlie      104     200

In [6]:
df_left = pd.merge(customers, orders, on='CustomerID', how='left')  # Left join on 'CustomerID'
print("Left Join:\n", df_left)

Left Join:
    CustomerID     Name  OrderID  Amount
0           1    Alice    101.0   250.0
1           1    Alice    103.0   300.0
2           2      Bob    102.0   150.0
3           2      Bob    105.0   100.0
4           3  Charlie    104.0   200.0
5           4    David      NaN     NaN
6           5      Eva      NaN     NaN

In [7]:
df_right = pd.merge(customers, orders, on='CustomerID', how='right')  # Right join on 'CustomerID'
print("Right Join:\n", df_right)

Right Join:
    CustomerID     Name  OrderID  Amount
0           1    Alice      101     250
1           2      Bob      102     150
2           1    Alice      103     300
3           3  Charlie      104     200
4           2      Bob      105     100

In [8]:
df_outer = pd.merge(customers, orders, on='CustomerID', how='outer')  # Outer join on 'CustomerID'
print("Outer Join:\n", df_outer)

Outer Join:
    CustomerID     Name  OrderID  Amount
0           1    Alice    101.0   250.0
1           1    Alice    103.0   300.0
2           2      Bob    102.0   150.0
3           2      Bob    105.0   100.0
4           3  Charlie    104.0   200.0
5           4    David      NaN     NaN
6           5      Eva      NaN     NaN

In [10]:
df_concat = pd.concat([customers, customers])  # Concatenate along rows (axis=0)
print("\nConcatenated Rows:\n", df_concat)

Concatenated Rows:
    CustomerID     Name
0           1    Alice
1           2      Bob
2           3  Charlie
3           4    David
4           5      Eva
0           1    Alice
1           2      Bob
2           3  Charlie
3           4    David
4           5      Eva

Topic 63 | Applying Functions - apply, map & pipe
This topic covers applying custom and built in functions using apply, map, and pipe. It also explains performance considerations and method chaining.

In [15]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=["order_date"])
df.info()  # Print information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [16]:
df['Payment_Type'] = df['payment_method'].map({
    'Card': 'Digital',
    'Wallet': 'Digital',
    'COD': 'Cash',
})

df['Payment_Type'].unique()  # Display unique values in the 'Payment_Type' column

array(['Digital', 'Cash'], dtype=object)

In [ ]:
df[['Payment_Type', 'payment_method']].head()  # Display the first few rows of 'Payment_Type' and 'payment_method' columns

  Payment_Type payment_method
0      Digital         Wallet
1      Digital           Card
2         Cash            COD
3      Digital         Wallet
4      Digital         Wallet

In [20]:
df.groupby('Payment_Type').size()    # Count the number of orders for each payment type

Payment_Type
Cash       1774
Digital    3226
dtype: int64

In [21]:
def revenue_category(row):
    if row['revenue'] > 500:
        return 'High'
    elif row['revenue'] >= 200:
        return 'Medium'
    else:
        return 'Low'

df['Revenue_Category'] = df.apply(revenue_category, axis=1)  # Apply the revenue_category function to each row

In [22]:
df['Revenue_Category'].value_counts()  # Count the number of orders in each revenue category

Revenue_Category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [24]:
df[['revenue', 'Revenue_Category']].sample(10)  # Display the first few rows of 'revenue' and 'Revenue_Category' columns

      revenue Revenue_Category
2816   197.45              Low
107   1021.84             High
1375   306.91           Medium
4689   250.40           Medium
4359  1140.16             High
1391   185.75              Low
2202  1901.23             High
967    347.83           Medium
152    278.49           Medium
958    110.10              Low

In [25]:
# pipe() - method chaining
def add_profit(data):
    data['Profit'] = data['revenue'] * 0.20 # Add a new column 'Profit' as 20% of 'revenue'
    return data

def add_net_revenue(data):
    data['Net_Revenue'] = data['revenue'] - data['Profit'] # Add a new column 'Net_Revenue' as 'revenue' minus 'Profit'
    return data

df = (
    df
    .pipe(add_profit)  # Apply the add_profit function
    .pipe(add_net_revenue)  # Apply the add_net_revenue function
)

In [26]:
df[["revenue", "Profit", "Net_Revenue"]].head()  # Display the first few rows of 'revenue', 'Profit', and 'Net_Revenue' columns

   revenue   Profit  Net_Revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848

Topic 64 | EDA(Exploratory Data Analysis) Key Questions & Mindset
This topic highlights how to approach EDA by defining goals, identifying feature types, and checking data quality. It also includes writing key EDA questions for a dataset.

Topic 65 | Descriptive Stats & Data Distributions
This topic explains how to compute descriptive statistics, quantiles, and frequency counts. It also covers skewness, kurtosis, and detecting extreme values using IQR.

In [27]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=["order_date"])
df.info()  # Print information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [29]:
df.shape

(5000, 12)

In [30]:
df.describe()  # Print summary statistics of the DataFrame

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [31]:
df[["unit_price", "revenue"]].describe()  # Print summary statistics of 'unit_price' and 'revenue' columns

        unit_price      revenue
count  5000.000000  5000.000000
mean    308.418774  1021.955148
std     169.259369   825.584219
min      15.150000    11.210000
25%     161.895000   354.527500
50%     309.890000   796.650000
75%     455.557500  1515.690000
max     599.960000  4119.330000

In [32]:
df['revenue'].quantile([0.25, 0.5, 0.75])  # Calculate the 25th, 50th, and 75th percentiles of the 'revenue' column

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [ ]:
# identifiying Skewness and Kurtosis
df['revenue'].mean(), df['revenue'].median()  # Calculate the mean and median of the 'revenue' column

(np.float64(1021.955148), np.float64(796.65))

In [34]:
df['revenue'].skew()

np.float64(1.0017064603000962)

In [35]:
df.groupby('product_category')['revenue'].describe()  # Calculate the mean revenue for each product category

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [36]:
df.groupby('product_category')['revenue'].mean()  # Calculate the mean revenue for each product category

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [37]:
# Uning IQR to understand spread
Q1 = df['revenue'].quantile(0.25)  # Calculate the first quartile (25th percentile)
Q3 = df['revenue'].quantile(0.75) # Calculate the third quartile (75th percentile)
IQR = Q3 - Q1  # Calculate the interquartile range (IQR)

Q1, Q3, IQR

(np.float64(354.5275), np.float64(1515.69), np.float64(1161.1625000000001))

In [38]:
(Q3 > Q1) and (IQR > 0)  # Check if Q3 is greater than Q1 and IQR is positive

np.True_

Topic 66 | Working with Datetime & Time Series Data
This topic covers parsing dates, setting datetime indexes, and resampling data across time periods. It highlights computing monthly totals and growth rates.

In [39]:
import pandas as pd
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates=["order_date"])
df.info()  # Print information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [40]:
# Setting datetime index
df = df.set_index('order_date')  # Set 'order_date' as the index of the DataFrame

In [41]:
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[ns]', name='order_date', length=5000, freq=None)

In [42]:
#Monthly Revenue Analysis
monthly_revenue = df['revenue'].resample('ME').sum()  # Resample the 'revenue' column by month and calculate the sum
monthly_revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [43]:
# Trend interpretation
monthly_revenue.pct_change()  # Calculate the percentage change in monthly revenue

order_date
2022-01-31         NaN
2022-02-28   -0.160450
2022-03-31    0.013387
2022-04-30    0.015595
2022-05-31    0.352391
                ...
2035-05-31    0.201727
2035-06-30   -0.245213
2035-07-31   -0.050021
2035-08-31    0.225950
2035-09-30   -0.831297
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [44]:
monthly_revenue.index.is_monotonic_increasing  # Check if the index is monotonically increasing

True

In [45]:
print(monthly_revenue.sum(), df['revenue'].sum())  # Print the total monthly revenue and the total revenue from the original DataFrame
monthly_revenue.sum() <= df['revenue'].sum()  # Check if the total monthly revenue is less than or equal to the total revenue from the original DataFrame

5109775.74 5109775.74

np.True_