# FIFA World Cup 2026 — Full Prediction Submission

**Methodology:** Predictions are based on:
- Current FIFA/Coca-Cola World Rankings (April 2026)
- Opta AI win probabilities and bookmaker odds (Spain 16%, France 12-13%, England 12%, Argentina 10%, Brazil 8-9%)
- Historical average goals per World Cup match (~2.5–2.6), corners (~10), yellow cards (~3), red cards (~0.25)
- Team strength differentials, group draw context, host nation advantages
- Round multipliers factored into confidence weighting

**Predicted Winner:** 🇪🇸 Spain

In [1]:
import pandas as pd
import numpy as np

print('Libraries loaded. Building predictions...')

Libraries loaded. Building predictions...

## Group Stage Fixtures & Predictions

All 72 group stage matches across Groups A–L.

In [6]:
# ── GROUP STAGE FIXTURES ─────────────────────────────────────────────────────
# 72 matches, Groups A–L
# Columns: match_id, group, home_team, away_team, date, venue

group_fixtures_data = [
    # ── GROUP A: Mexico, South Africa, South Korea, Czechia ──
    (1,  'A', 'Mexico',       'South Africa', '2026-06-11', 'Estadio Azteca, Mexico City'),
    (2,  'A', 'South Korea',  'Czechia',       '2026-06-12', 'SoFi Stadium, Los Angeles'),
    (3,  'A', 'Mexico',       'South Korea',   '2026-06-18', 'Estadio Akron, Guadalajara'),
    (4,  'A', 'Czechia',      'South Africa',  '2026-06-18', 'Mercedes-Benz Stadium, Atlanta'),
    (5,  'A', 'Mexico',       'Czechia',        '2026-06-25', 'Estadio Akron, Guadalajara'),
    (6,  'A', 'South Africa', 'South Korea',   '2026-06-25', 'SoFi Stadium, Los Angeles'),
   # ── GROUP B: Canada, Switzerland, Qatar, Bosnia-Herzegovina ──
    (7,  'B', 'Canada',             'Bosnia-Herzegovina', '2026-06-12', 'BMO Field, Toronto'),
    (8,  'B', 'Qatar',              'Switzerland',        '2026-06-13', "Levi's Stadium, San Francisco Bay Area"),
    (9,  'B', 'Canada',             'Qatar',              '2026-06-18', 'BC Place, Vancouver'),
    (10, 'B', 'Switzerland',        'Bosnia-Herzegovina', '2026-06-19', 'BMO Field, Toronto'),
    (11, 'B', 'Canada',             'Switzerland',        '2026-06-25', "Levi's Stadium, San Francisco Bay Area"),
    (12, 'B', 'Bosnia-Herzegovina', 'Qatar',              '2026-06-25', 'BC Place, Vancouver'),
    # ── GROUP C: Brazil, Morocco, Scotland, Haiti ──
    (13, 'C', 'Brazil',   'Scotland', '2026-06-13', 'Gillette Stadium, Boston'),
    (14, 'C', 'Morocco',  'Haiti',    '2026-06-13', 'BC Place, Vancouver'),
    (15, 'C', 'Brazil',   'Haiti',    '2026-06-19', 'Lincoln Financial Field, Philadelphia'),
    (16, 'C', 'Scotland', 'Morocco',  '2026-06-19', 'Gillette Stadium, Boston'),
    (17, 'C', 'Brazil',   'Morocco',  '2026-06-26', 'Estadio BBVA, Monterrey'),
    (18, 'C', 'Haiti',    'Scotland', '2026-06-26', 'Lincoln Financial Field, Philadelphia'),
    # ── GROUP D: USA, Paraguay, Australia, Türkiye ──
    (19, 'D', 'USA',       'Paraguay',  '2026-06-12', 'SoFi Stadium, Los Angeles'),
    (20, 'D', 'Australia', 'Türkiye',   '2026-06-13', 'Arrowhead Stadium, Kansas City'),
    (21, 'D', 'USA',       'Australia', '2026-06-19', 'Lumen Field, Seattle'),
    (22, 'D', 'Türkiye',   'Paraguay',  '2026-06-19', "Levi's Stadium, San Francisco Bay Area"),
    (23, 'D', 'USA',       'Türkiye',   '2026-06-25', 'Lumen Field, Seattle'),
    (24, 'D', 'Paraguay',  'Australia', '2026-06-25', 'Arrowhead Stadium, Kansas City'),
    # ── GROUP E: Germany, Curaçao, Ivory Coast, Ecuador ──
    (25, 'E', 'Germany',     'Curaçao',     '2026-06-14', 'NRG Stadium, Houston'),
    (26, 'E', 'Ivory Coast', 'Ecuador',     '2026-06-14', 'Lincoln Financial Field, Philadelphia'),
    (27, 'E', 'Germany',     'Ivory Coast', '2026-06-20', 'Gillette Stadium, Boston'),
    (28, 'E', 'Ecuador',     'Curaçao',     '2026-06-20', 'NRG Stadium, Houston'),
    (29, 'E', 'Germany',     'Ecuador',     '2026-06-25', 'AT&T Stadium, Dallas'),
    (30, 'E', 'Curaçao',     'Ivory Coast', '2026-06-25', 'Lincoln Financial Field, Philadelphia'),
    # ── GROUP F: Netherlands, Japan, Sweden, Tunisia ──
    (31, 'F', 'Netherlands', 'Japan',       '2026-06-14', 'AT&T Stadium, Dallas'),
    (32, 'F', 'Sweden',      'Tunisia',     '2026-06-14', 'Estadio BBVA, Monterrey'),
    (33, 'F', 'Netherlands', 'Sweden',      '2026-06-20', 'Arrowhead Stadium, Kansas City'),
    (34, 'F', 'Tunisia',     'Japan',       '2026-06-20', 'AT&T Stadium, Dallas'),
    (35, 'F', 'Netherlands', 'Tunisia',     '2026-06-26', 'Gillette Stadium, Boston'),
    (36, 'F', 'Japan',       'Sweden',      '2026-06-26', 'Estadio BBVA, Monterrey'),
    # ── GROUP G: Belgium, Egypt, Iran, New Zealand ──
    (37, 'G', 'Belgium',     'Egypt',       '2026-06-15', 'BC Place, Vancouver'),
    (38, 'G', 'Iran',        'New Zealand', '2026-06-15', 'SoFi Stadium, Los Angeles'),
    (39, 'G', 'Belgium',     'Iran',        '2026-06-21', 'Arrowhead Stadium, Kansas City'),
    (40, 'G', 'New Zealand', 'Egypt',       '2026-06-21', 'BC Place, Vancouver'),
    (41, 'G', 'Belgium',     'New Zealand', '2026-06-26', 'Lumen Field, Seattle'),
    (42, 'G', 'Egypt',       'Iran',        '2026-06-26', 'Arrowhead Stadium, Kansas City'),
    # ── GROUP H: Spain, Cape Verde, Saudi Arabia, Uruguay ──
    (43, 'H', 'Spain',        'Cape Verde',  '2026-06-15', 'Mercedes-Benz Stadium, Atlanta'),
    (44, 'H', 'Saudi Arabia', 'Uruguay',     '2026-06-15', 'Hard Rock Stadium, Miami'),
    (45, 'H', 'Spain',        'Saudi Arabia','2026-06-21', "Levi's Stadium, San Francisco Bay Area"),
    (46, 'H', 'Uruguay',      'Cape Verde',  '2026-06-21', 'Hard Rock Stadium, Miami'),
    (47, 'H', 'Spain',        'Uruguay',     '2026-06-26', 'Mercedes-Benz Stadium, Atlanta'),
    (48, 'H', 'Cape Verde',   'Saudi Arabia','2026-06-26', 'NRG Stadium, Houston'),
    # ── GROUP I: France, Senegal, Iraq, Norway ──
    (49, 'I', 'France',  'Senegal', '2026-06-16', 'MetLife Stadium, New York/New Jersey'),
    (50, 'I', 'Iraq',    'Norway',  '2026-06-16', 'Gillette Stadium, Boston'),
    (51, 'I', 'France',  'Iraq',    '2026-06-22', 'AT&T Stadium, Dallas'),
    (52, 'I', 'Norway',  'Senegal', '2026-06-22', 'MetLife Stadium, New York/New Jersey'),
    (53, 'I', 'France',  'Norway',  '2026-06-27', 'Lumen Field, Seattle'),
    (54, 'I', 'Senegal', 'Iraq',    '2026-06-27', 'AT&T Stadium, Dallas'),
    # ── GROUP J: Argentina, Algeria, Austria, Jordan ──
    (55, 'J', 'Argentina', 'Algeria', '2026-06-16', 'Arrowhead Stadium, Kansas City'),
    (56, 'J', 'Austria',   'Jordan',  '2026-06-16', "Levi's Stadium, San Francisco Bay Area"),
    (57, 'J', 'Argentina', 'Austria', '2026-06-22', 'NRG Stadium, Houston'),
    (58, 'J', 'Jordan',    'Algeria', '2026-06-22', 'Arrowhead Stadium, Kansas City'),
    (59, 'J', 'Argentina', 'Jordan',  '2026-06-27', 'MetLife Stadium, New York/New Jersey'),
    (60, 'J', 'Algeria',   'Austria', '2026-06-27', 'NRG Stadium, Houston'),
    # ── GROUP K: Portugal, Colombia, Uzbekistan, DR Congo ──
    (61, 'K', 'Portugal',  'DR Congo',   '2026-06-17', 'NRG Stadium, Houston'),
    (62, 'K', 'Colombia',  'Uzbekistan', '2026-06-17', 'Estadio Azteca, Mexico City'),
    (63, 'K', 'Portugal',  'Uzbekistan', '2026-06-23', 'NRG Stadium, Houston'),
    (64, 'K', 'DR Congo',  'Colombia',   '2026-06-23', 'Estadio Azteca, Mexico City'),
    (65, 'K', 'Portugal',  'Colombia',   '2026-06-27', 'Hard Rock Stadium, Miami'),
    (66, 'K', 'Uzbekistan','DR Congo',   '2026-06-27', 'Mercedes-Benz Stadium, Atlanta'),
    # ── GROUP L: England, Croatia, Ghana, Panama ──
    (67, 'L', 'England',  'Ghana',   '2026-06-17', 'MetLife Stadium, New York/New Jersey'),
    (68, 'L', 'Croatia',  'Panama',  '2026-06-17', 'AT&T Stadium, Dallas'),
    (69, 'L', 'England',  'Croatia', '2026-06-23', 'Lincoln Financial Field, Philadelphia'),
    (70, 'L', 'Panama',   'Ghana',   '2026-06-23', 'BMO Field, Toronto'),
    (71, 'L', 'England',  'Panama',  '2026-06-27', 'MetLife Stadium, New York/New Jersey'),
    (72, 'L', 'Ghana',    'Croatia', '2026-06-27', 'Lincoln Financial Field, Philadelphia'),
]

group_fixtures = pd.DataFrame(
    group_fixtures_data,
    columns=['match_id', 'group', 'home_team', 'away_team', 'date', 'venue']
)

print(f'Group fixtures loaded: {len(group_fixtures)} matches')
group_fixtures.head(10)

Group fixtures loaded: 72 matches

,match_id,group,home_team,away_team,date,venue
0,1,A,Mexico,South Africa,2026-06-11,"Estadio Azteca, Mexico City"
1,2,A,South Korea,Czechia,2026-06-12,"SoFi Stadium, Los Angeles"
2,3,A,Mexico,South Korea,2026-06-18,"Estadio Akron, Guadalajara"
3,4,A,Czechia,South Africa,2026-06-18,"Mercedes-Benz Stadium, Atlanta"
4,5,A,Mexico,Czechia,2026-06-25,"Estadio Akron, Guadalajara"
5,6,A,South Africa,South Korea,2026-06-25,"SoFi Stadium, Los Angeles"
6,7,B,Canada,Bosnia-Herzegovina,2026-06-12,"BMO Field, Toronto"
7,8,B,Qatar,Switzerland,2026-06-13,"Levi's Stadium, San Francisco Bay Area"
8,9,B,Canada,Qatar,2026-06-18,"BC Place, Vancouver"
9,10,B,Switzerland,Bosnia-Herzegovina,2026-06-19,"BMO Field, Toronto"

## Prediction Logic

**Goals:** Calibrated to historical WC average (~2.6 goals/match). Strong teams vs weak = 2-0 or 3-0. Close matchups = 1-1 draw. Host-nation effect (+0.3 goals) applied to Mexico, USA, Canada.

**Corners:** Historical average ~10/match. High-press teams (Germany, Spain, England) inflate. Low-block teams deflate.

**Yellow cards:** Average ~3/match. Knockout-adjacent group matches and physical games push higher.

**Red cards:** Rare (~0.25/match); default 0, occasional 1 for volatile fixtures.

**Winning team:** Derived from scoreline prediction.

In [7]:
# ── GROUP STAGE PREDICTIONS ───────────────────────────────────────────────────
# Format: match_id, home_goals, away_goals, corners, yellow_cards, red_cards
# winning_team derived automatically from scoreline

pred_data = [
    # GROUP A ─ Mexico (host/strong), South Africa (weak), South Korea (mid), Czechia (mid)
    (1,  2, 0, 10, 3, 0),  # Mexico vs South Africa
    (2,  1, 1, 9,  3, 0),  # South Korea vs Czechia
    (3,  2, 1, 10, 3, 0),  # Mexico vs South Korea
    (4,  1, 0, 9,  3, 0),  # Czechia vs South Africa
    (5,  2, 1, 10, 3, 0),  # Mexico vs Czechia
    (6,  1, 1, 9,  3, 0),  # South Africa vs South Korea
    # GROUP B ─ Canada (host/strong), Switzerland (solid), Qatar (weak), Bosnia (mid)
    (7,  2, 0, 10, 3, 0),  # Canada vs Bosnia
    (8,  0, 2, 9,  2, 0),  # Qatar vs Switzerland
    (9,  2, 0, 10, 2, 0),  # Canada vs Qatar
    (10, 2, 0, 10, 3, 0),  # Switzerland vs Bosnia
    (11, 1, 2, 10, 3, 0),  # Canada vs Switzerland
    (12, 1, 1, 8,  3, 1),  # Bosnia vs Qatar
    # GROUP C ─ Brazil (top), Morocco (strong), Scotland (mid), Haiti (weak)
    (13, 3, 0, 11, 2, 0),  # Brazil vs Scotland
    (14, 2, 0, 9,  3, 0),  # Morocco vs Haiti
    (15, 4, 0, 11, 2, 0),  # Brazil vs Haiti
    (16, 1, 2, 10, 3, 0),  # Scotland vs Morocco
    (17, 2, 1, 11, 3, 0),  # Brazil vs Morocco
    (18, 0, 2, 8,  3, 0),  # Haiti vs Scotland
    # GROUP D ─ USA (host/strong), Türkiye (mid-strong), Paraguay (mid), Australia (mid)
    (19, 2, 0, 10, 3, 0),  # USA vs Paraguay
    (20, 1, 1, 9,  3, 0),  # Australia vs Türkiye
    (21, 2, 0, 10, 2, 0),  # USA vs Australia
    (22, 2, 1, 10, 4, 1),  # Türkiye vs Paraguay
    (23, 1, 1, 10, 3, 0),  # USA vs Türkiye
    (24, 1, 1, 9,  3, 0),  # Paraguay vs Australia
    # GROUP E ─ Germany (top), Ecuador (mid), Ivory Coast (mid), Curaçao (weak)
    (25, 4, 0, 12, 2, 0),  # Germany vs Curaçao
    (26, 1, 1, 9,  3, 0),  # Ivory Coast vs Ecuador
    (27, 2, 1, 11, 3, 0),  # Germany vs Ivory Coast
    (28, 2, 1, 10, 3, 0),  # Ecuador vs Curaçao
    (29, 2, 1, 11, 3, 0),  # Germany vs Ecuador
    (30, 1, 2, 9,  3, 0),  # Curaçao vs Ivory Coast
    # GROUP F ─ Netherlands (strong), Japan (strong), Sweden (mid), Tunisia (weak)
    (31, 2, 1, 11, 3, 0),  # Netherlands vs Japan
    (32, 2, 0, 10, 3, 0),  # Sweden vs Tunisia
    (33, 2, 1, 10, 3, 0),  # Netherlands vs Sweden
    (34, 0, 2, 9,  3, 0),  # Tunisia vs Japan
    (35, 3, 0, 11, 2, 0),  # Netherlands vs Tunisia
    (36, 2, 1, 10, 3, 0),  # Japan vs Sweden
    # GROUP G ─ Belgium (strong), Egypt (mid), Iran (mid), New Zealand (weak)
    (37, 2, 0, 10, 3, 0),  # Belgium vs Egypt
    (38, 1, 0, 9,  3, 0),  # Iran vs New Zealand
    (39, 2, 0, 10, 3, 0),  # Belgium vs Iran
    (40, 1, 1, 8,  3, 0),  # New Zealand vs Egypt
    (41, 3, 0, 10, 2, 0),  # Belgium vs New Zealand
    (42, 2, 1, 10, 3, 1),  # Egypt vs Iran
    # GROUP H ─ Spain (top/favourite), Uruguay (strong), Saudi Arabia (mid), Cape Verde (weak)
    (43, 4, 0, 12, 2, 0),  # Spain vs Cape Verde
    (44, 1, 1, 9,  3, 0),  # Saudi Arabia vs Uruguay
    (45, 3, 0, 12, 2, 0),  # Spain vs Saudi Arabia
    (46, 2, 0, 9,  3, 0),  # Uruguay vs Cape Verde
    (47, 2, 1, 11, 3, 0),  # Spain vs Uruguay
    (48, 0, 2, 8,  3, 0),  # Cape Verde vs Saudi Arabia
    # GROUP I ─ France (top), Senegal (strong), Norway (strong), Iraq (weak)
    (49, 2, 1, 11, 3, 0),  # France vs Senegal
    (50, 0, 2, 9,  3, 0),  # Iraq vs Norway
    (51, 3, 0, 11, 2, 0),  # France vs Iraq
    (52, 2, 1, 10, 3, 0),  # Norway vs Senegal
    (53, 2, 1, 11, 3, 0),  # France vs Norway
    (54, 2, 0, 9,  3, 0),  # Senegal vs Iraq
    # GROUP J ─ Argentina (top), Austria (mid-strong), Algeria (mid), Jordan (weak)
    (55, 3, 0, 11, 2, 0),  # Argentina vs Algeria
    (56, 2, 0, 9,  3, 0),  # Austria vs Jordan
    (57, 2, 1, 11, 3, 0),  # Argentina vs Austria
    (58, 1, 2, 9,  3, 0),  # Jordan vs Algeria
    (59, 2, 0, 10, 2, 0),  # Argentina vs Jordan
    (60, 1, 1, 9,  3, 0),  # Algeria vs Austria
    # GROUP K ─ Portugal (top), Colombia (strong), Uzbekistan (mid), DR Congo (mid)
    (61, 3, 0, 11, 2, 0),  # Portugal vs DR Congo
    (62, 2, 0, 10, 3, 0),  # Colombia vs Uzbekistan
    (63, 3, 1, 11, 3, 0),  # Portugal vs Uzbekistan
    (64, 0, 2, 9,  3, 0),  # DR Congo vs Colombia
    (65, 2, 1, 11, 3, 0),  # Portugal vs Colombia
    (66, 1, 1, 8,  3, 0),  # Uzbekistan vs DR Congo
    # GROUP L ─ England (top), Croatia (mid-strong), Ghana (mid), Panama (weak)
    (67, 3, 0, 11, 2, 0),  # England vs Ghana
    (68, 2, 0, 10, 3, 0),  # Croatia vs Panama
    (69, 2, 1, 11, 3, 0),  # England vs Croatia
    (70, 1, 1, 8,  4, 1),  # Panama vs Ghana
    (71, 4, 0, 12, 2, 0),  # England vs Panama
    (72, 1, 2, 10, 3, 0),  # Ghana vs Croatia
]

pred_df = pd.DataFrame(
    pred_data,
    columns=['match_id', 'predicted_home_goals', 'predicted_away_goals',
             'corners', 'yellow_cards', 'red_cards']
)

# Derive winning_team from score
def get_winner(row):
    if row['predicted_home_goals'] > row['predicted_away_goals']:
        return 'home'
    elif row['predicted_home_goals'] < row['predicted_away_goals']:
        return 'away'
    else:
        return 'draw'

pred_df['winning_team'] = pred_df.apply(get_winner, axis=1)

# Merge with fixture info
group_predictions = group_fixtures.merge(pred_df, on='match_id')

print(f'Group predictions complete: {len(group_predictions)} matches')
print(f"Winner distribution: {group_predictions['winning_team'].value_counts().to_dict()}")
group_predictions.head(10)

Group predictions complete: 72 matches
Winner distribution: {'home': 49, 'draw': 12, 'away': 11}

,match_id,group,home_team,away_team,date,venue,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,winning_team
0,1,A,Mexico,South Africa,2026-06-11,"Estadio Azteca, Mexico City",2,0,10,3,0,home
1,2,A,South Korea,Czechia,2026-06-12,"SoFi Stadium, Los Angeles",1,1,9,3,0,draw
2,3,A,Mexico,South Korea,2026-06-18,"Estadio Akron, Guadalajara",2,1,10,3,0,home
3,4,A,Czechia,South Africa,2026-06-18,"Mercedes-Benz Stadium, Atlanta",1,0,9,3,0,home
4,5,A,Mexico,Czechia,2026-06-25,"Estadio Akron, Guadalajara",2,1,10,3,0,home
5,6,A,South Africa,South Korea,2026-06-25,"SoFi Stadium, Los Angeles",1,1,9,3,0,draw
6,7,B,Canada,Bosnia-Herzegovina,2026-06-12,"BMO Field, Toronto",2,0,10,3,0,home
7,8,B,Qatar,Switzerland,2026-06-13,"Levi's Stadium, San Francisco Bay Area",0,2,9,2,0,away
8,9,B,Canada,Qatar,2026-06-18,"BC Place, Vancouver",2,0,10,2,0,home
9,10,B,Switzerland,Bosnia-Herzegovina,2026-06-19,"BMO Field, Toronto",2,0,10,3,0,home

In [8]:
# ── VERIFY: No None values in group predictions ───────────────────────────────
assert group_predictions[['predicted_home_goals','predicted_away_goals',
                           'corners','yellow_cards','red_cards','winning_team']].isnull().sum().sum() == 0
assert len(group_predictions) == 72
print('✅ All 72 group stage predictions filled — no None values.')

✅ All 72 group stage predictions filled — no None values.

## Predicted Group Stage Standings

Used to project the knockout bracket.

| Group | 1st         | 2nd          | 3rd (potential best 3rd) |
|-------|-------------|--------------|---------------------------|
| A     | Mexico      | South Korea  | Czechia                   |
| B     | Switzerland | Canada       | Bosnia-Herzegovina        |
| C     | Brazil      | Morocco      | Scotland                  |
| D     | USA         | Türkiye      | Australia                 |
| E     | Germany     | Ecuador      | Ivory Coast               |
| F     | Netherlands | Japan        | Sweden                    |
| G     | Belgium     | Egypt        | Iran                      |
| H     | Spain       | Uruguay      | Saudi Arabia              |
| I     | France      | Norway       | Senegal                   |
| J     | Argentina   | Austria      | Algeria                   |
| K     | Portugal    | Colombia     | DR Congo                  |
| L     | England     | Croatia      | Ghana                     |

**8 best 3rd-place teams advancing:** Scotland, Ivory Coast, Australia, Sweden, Senegal, Algeria, DR Congo, Ghana

In [9]:
# ── KNOCKOUT STAGE SLOTS ──────────────────────────────────────────────────────
knockout_slots_data = [
    # Round of 32 (×1)
    (73,  'Round of 32', 1, 'Runner-up Group A',  'Runner-up Group B'),
    (74,  'Round of 32', 1, 'Winner Group E',     '3rd Group A/B/C/D/F'),
    (75,  'Round of 32', 1, 'Winner Group F',     'Runner-up Group C'),
    (76,  'Round of 32', 1, 'Winner Group C',     'Runner-up Group F'),
    (77,  'Round of 32', 1, 'Winner Group I',     '3rd Group C/D/F/G/H'),
    (78,  'Round of 32', 1, 'Runner-up Group E',  'Runner-up Group I'),
    (79,  'Round of 32', 1, 'Winner Group A',     '3rd Group C/E/F/H/I'),
    (80,  'Round of 32', 1, 'Winner Group L',     '3rd Group E/H/I/J/K'),
    (81,  'Round of 32', 1, 'Runner-up Group D',  'Runner-up Group L'),
    (82,  'Round of 32', 1, 'Winner Group G',     '3rd Group A/E/H/I/J'),
    (83,  'Round of 32', 1, 'Winner Group D',     '3rd Group A/B/C/G'),
    (84,  'Round of 32', 1, 'Runner-up Group G',  'Runner-up Group H'),
    (85,  'Round of 32', 1, 'Winner Group H',     '3rd Group D/E/F/G'),
    (86,  'Round of 32', 1, 'Winner Group B',     '3rd Group G/H/I/J/K/L'),
    (87,  'Round of 32', 1, 'Winner Group K',     'Runner-up Group J'),
    (88,  'Round of 32', 1, 'Winner Group J',     'Runner-up Group K'),
    # Round of 16 (×2)
    (89,  'Round of 16', 2, 'Winner Match 73',    'Winner Match 74'),
    (90,  'Round of 16', 2, 'Winner Match 75',    'Winner Match 76'),
    (91,  'Round of 16', 2, 'Winner Match 77',    'Winner Match 78'),
    (92,  'Round of 16', 2, 'Winner Match 79',    'Winner Match 80'),
    (93,  'Round of 16', 2, 'Winner Match 81',    'Winner Match 82'),
    (94,  'Round of 16', 2, 'Winner Match 83',    'Winner Match 84'),
    (95,  'Round of 16', 2, 'Winner Match 85',    'Winner Match 86'),
    (96,  'Round of 16', 2, 'Winner Match 87',    'Winner Match 88'),
    # Quarter-finals (×4)
    (97,  'Quarter-final', 4, 'Winner Match 89',  'Winner Match 90'),
    (98,  'Quarter-final', 4, 'Winner Match 91',  'Winner Match 92'),
    (99,  'Quarter-final', 4, 'Winner Match 93',  'Winner Match 94'),
    (100, 'Quarter-final', 4, 'Winner Match 95',  'Winner Match 96'),
    # Semi-finals (×8)
    (101, 'Semi-final', 8, 'Winner Match 97',  'Winner Match 98'),
    (102, 'Semi-final', 8, 'Winner Match 99',  'Winner Match 100'),
    # Third-place (×8)
    (103, 'Third-place playoff', 8, 'Loser Match 101', 'Loser Match 102'),
    # Final (×16)
    (104, 'Final', 16, 'Winner Match 101', 'Winner Match 102'),
]

knockout_slots = pd.DataFrame(
    knockout_slots_data,
    columns=['match_id', 'round', 'multiplier', 'slot_home', 'slot_away']
)

print(f'Knockout slots loaded: {len(knockout_slots)} matches')
knockout_slots

Knockout slots loaded: 32 matches

,match_id,round,multiplier,slot_home,slot_away
0,73,Round of 32,1,Runner-up Group A,Runner-up Group B
1,74,Round of 32,1,Winner Group E,3rd Group A/B/C/D/F
2,75,Round of 32,1,Winner Group F,Runner-up Group C
3,76,Round of 32,1,Winner Group C,Runner-up Group F
4,77,Round of 32,1,Winner Group I,3rd Group C/D/F/G/H
5,78,Round of 32,1,Runner-up Group E,Runner-up Group I
6,79,Round of 32,1,Winner Group A,3rd Group C/E/F/H/I
7,80,Round of 32,1,Winner Group L,3rd Group E/H/I/J/K
8,81,Round of 32,1,Runner-up Group D,Runner-up Group L
9,82,Round of 32,1,Winner Group G,3rd Group A/E/H/I/J
10,83,Round of 32,1,Winner Group D,3rd Group A/B/C/G
11,84,Round of 32,1,Runner-up Group G,Runner-up Group H
12,85,Round of 32,1,Winner Group H,3rd Group D/E/F/G
13,86,Round of 32,1,Winner Group B,3rd Group G/H/I/J/K/L
14,87,Round of 32,1,Winner Group K,Runner-up Group J
15,88,Round of 32,1,Winner Group J,Runner-up Group K
16,89,Round of 16,2,Winner Match 73,Winner Match 74
17,90,Round of 16,2,Winner Match 75,Winner Match 76
18,91,Round of 16,2,Winner Match 77,Winner Match 78
19,92,Round of 16,2,Winner Match 79,Winner Match 80
20,93,Round of 16,2,Winner Match 81,Winner Match 82
21,94,Round of 16,2,Winner Match 83,Winner Match 84
22,95,Round of 16,2,Winner Match 85,Winner Match 86
23,96,Round of 16,2,Winner Match 87,Winner Match 88
24,97,Quarter-final,4,Winner Match 89,Winner Match 90
25,98,Quarter-final,4,Winner Match 91,Winner Match 92
26,99,Quarter-final,4,Winner Match 93,Winner Match 94
27,100,Quarter-final,4,Winner Match 95,Winner Match 96
28,101,Semi-final,8,Winner Match 97,Winner Match 98
29,102,Semi-final,8,Winner Match 99,Winner Match 100
30,103,Third-place playoff,8,Loser Match 101,Loser Match 102
31,104,Final,16,Winner Match 101,Winner Match 102

In [10]:
# ── KNOCKOUT STAGE PREDICTIONS ────────────────────────────────────────────────
# Based on predicted group standings & team strength (Opta/bookmaker probabilities)
#
# Pathway A: Groups A/B/C/D/E/F  → one side of bracket
# Pathway B: Groups G/H/I/J/K/L  → other side of bracket
# FIFA 2-pathway system keeps Spain & Argentina apart until SF
#
# Predicted bracket highlights:
#   Spain path:    Spain → Uruguay/Saudi → Belgium/Egypt → Germany/Ecuador → Argentina → FINAL
#   France path:   France → Norway → Netherlands → Brazil → England → FINAL
#   Predicted Final: Spain vs France  →  Spain wins 2-1 (AET, no penalties)

knockout_pred_data = [
    # ── ROUND OF 32 ── (multiplier ×1)
    # M73: Runner-up A (South Korea) vs Runner-up B (Canada)
    (73,  'South Korea',  'Canada',      1, 2, 10, 3, 0, 'home', False),
    # M74: Winner E (Germany) vs 3rd best (Scotland)
    (74,  'Germany',      'Scotland',    2, 0, 10, 2, 0, 'home', False),
    # M75: Winner F (Netherlands) vs Runner-up C (Morocco)
    (75,  'Netherlands',  'Morocco',     1, 1, 10, 3, 0, 'home', False),
    # M76: Winner C (Brazil) vs Runner-up F (Japan)
    (76,  'Brazil',       'Japan',       2, 0, 11, 2, 0, 'home', False),
    # M77: Winner I (France) vs 3rd best (Senegal)
    (77,  'France',       'Senegal',     2, 0, 10, 3, 0, 'home', False),
    # M78: Runner-up E (Ecuador) vs Runner-up I (Norway)
    (78,  'Ecuador',      'Norway',      1, 2, 10, 3, 0, 'away', False),
    # M79: Winner A (Mexico) vs 3rd best (Ivory Coast)
    (79,  'Mexico',       'Ivory Coast', 2, 1, 10, 3, 0, 'home', False),
    # M80: Winner L (England) vs 3rd best (Algeria)
    (80,  'England',      'Algeria',     2, 0, 10, 2, 0, 'home', False),
    # M81: Runner-up D (Türkiye) vs Runner-up L (Croatia)
    (81,  'Türkiye',      'Croatia',     1, 1, 10, 4, 1, 'home', True),
    # M82: Winner G (Belgium) vs 3rd best (Sweden)
    (82,  'Belgium',      'Sweden',      2, 0, 10, 3, 0, 'home', False),
    # M83: Winner D (USA) vs 3rd best (Australia)
    (83,  'USA',          'Australia',   2, 0, 10, 2, 0, 'home', False),
    # M84: Runner-up G (Egypt) vs Runner-up H (Uruguay)
    (84,  'Egypt',        'Uruguay',     0, 2, 9,  3, 0, 'away', False),
    # M85: Winner H (Spain) vs 3rd best (DR Congo)
    (85,  'Spain',        'DR Congo',    4, 0, 12, 2, 0, 'home', False),
    # M86: Winner B (Switzerland) vs 3rd best (Ghana)
    (86,  'Switzerland',  'Ghana',       2, 1, 10, 3, 0, 'home', False),
    # M87: Winner K (Portugal) vs Runner-up J (Austria)
    (87,  'Portugal',     'Austria',     2, 1, 11, 3, 0, 'home', False),
    # M88: Winner J (Argentina) vs Runner-up K (Colombia)
    (88,  'Argentina',    'Colombia',    2, 1, 10, 3, 0, 'home', False),

    # ── ROUND OF 16 ── (multiplier ×2)
    # M89: W73 (South Korea) vs W74 (Germany)
    (89,  'South Korea',  'Germany',     0, 2, 10, 3, 0, 'away', False),
    # M90: W75 (Netherlands) vs W76 (Brazil)
    (90,  'Netherlands',  'Brazil',      1, 2, 11, 3, 0, 'away', False),
    # M91: W77 (France) vs W78 (Norway)
    (91,  'France',       'Norway',      2, 1, 10, 2, 0, 'home', False),
    # M92: W79 (Mexico) vs W80 (England)
    (92,  'Mexico',       'England',     0, 2, 10, 3, 0, 'away', False),
    # M93: W81 (Türkiye*pen) vs W82 (Belgium)
    (93,  'Türkiye',      'Belgium',     1, 2, 10, 4, 0, 'away', False),
    # M94: W83 (USA) vs W84 (Uruguay)
    (94,  'USA',          'Uruguay',     1, 2, 10, 3, 0, 'away', False),
    # M95: W85 (Spain) vs W86 (Switzerland)
    (95,  'Spain',        'Switzerland', 3, 0, 12, 2, 0, 'home', False),
    # M96: W87 (Portugal) vs W88 (Argentina)
    (96,  'Portugal',     'Argentina',   1, 2, 11, 3, 0, 'away', False),

    # ── QUARTER-FINALS ── (multiplier ×4)
    # M97: W89 (Germany) vs W90 (Brazil)
    (97,  'Germany',   'Brazil',    1, 2, 10, 3, 0, 'away', False),
    # M98: W91 (France) vs W92 (England)
    (98,  'France',    'England',   2, 1, 10, 3, 0, 'home', False),
    # M99: W93 (Belgium) vs W94 (Uruguay)
    (99,  'Belgium',   'Uruguay',   1, 1, 10, 3, 0, 'away', True),
    # M100: W95 (Spain) vs W96 (Argentina)
    (100, 'Spain',     'Argentina', 2, 1, 11, 3, 0, 'home', False),

    # ── SEMI-FINALS ── (multiplier ×8)
    # M101: W97 (Brazil) vs W98 (France)
    (101, 'Brazil',  'France',  1, 2, 10, 3, 0, 'away', False),
    # M102: W99 (Uruguay*pen) vs W100 (Spain)
    (102, 'Uruguay', 'Spain',   0, 2, 10, 2, 0, 'away', False),

    # ── THIRD-PLACE PLAYOFF ── (multiplier ×8)
    # M103: Brazil vs Uruguay
    (103, 'Brazil',  'Uruguay', 2, 1, 10, 3, 0, 'home', False),

    # ── FINAL ── (multiplier ×16)  🏆 Spain vs France
    (104, 'France',  'Spain',   1, 2, 10, 3, 0, 'away', False),
]

ko_pred_df = pd.DataFrame(
    knockout_pred_data,
    columns=[
        'match_id', 'predicted_home_team', 'predicted_away_team',
        'predicted_home_goals', 'predicted_away_goals',
        'corners', 'yellow_cards', 'red_cards',
        'match_winner', 'penalties'
    ]
)

knockout_predictions = knockout_slots.merge(ko_pred_df, on='match_id')

print(f'Knockout predictions complete: {len(knockout_predictions)} matches')
knockout_predictions

Knockout predictions complete: 32 matches

,match_id,round,multiplier,slot_home,slot_away,predicted_home_team,predicted_away_team,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,match_winner,penalties
0,73,Round of 32,1,Runner-up Group A,Runner-up Group B,South Korea,Canada,1,2,10,3,0,home,False
1,74,Round of 32,1,Winner Group E,3rd Group A/B/C/D/F,Germany,Scotland,2,0,10,2,0,home,False
2,75,Round of 32,1,Winner Group F,Runner-up Group C,Netherlands,Morocco,1,1,10,3,0,home,False
3,76,Round of 32,1,Winner Group C,Runner-up Group F,Brazil,Japan,2,0,11,2,0,home,False
4,77,Round of 32,1,Winner Group I,3rd Group C/D/F/G/H,France,Senegal,2,0,10,3,0,home,False
5,78,Round of 32,1,Runner-up Group E,Runner-up Group I,Ecuador,Norway,1,2,10,3,0,away,False
6,79,Round of 32,1,Winner Group A,3rd Group C/E/F/H/I,Mexico,Ivory Coast,2,1,10,3,0,home,False
7,80,Round of 32,1,Winner Group L,3rd Group E/H/I/J/K,England,Algeria,2,0,10,2,0,home,False
8,81,Round of 32,1,Runner-up Group D,Runner-up Group L,Türkiye,Croatia,1,1,10,4,1,home,True
9,82,Round of 32,1,Winner Group G,3rd Group A/E/H/I/J,Belgium,Sweden,2,0,10,3,0,home,False
10,83,Round of 32,1,Winner Group D,3rd Group A/B/C/G,USA,Australia,2,0,10,2,0,home,False
11,84,Round of 32,1,Runner-up Group G,Runner-up Group H,Egypt,Uruguay,0,2,9,3,0,away,False
12,85,Round of 32,1,Winner Group H,3rd Group D/E/F/G,Spain,DR Congo,4,0,12,2,0,home,False
13,86,Round of 32,1,Winner Group B,3rd Group G/H/I/J/K/L,Switzerland,Ghana,2,1,10,3,0,home,False
14,87,Round of 32,1,Winner Group K,Runner-up Group J,Portugal,Austria,2,1,11,3,0,home,False
15,88,Round of 32,1,Winner Group J,Runner-up Group K,Argentina,Colombia,2,1,10,3,0,home,False
16,89,Round of 16,2,Winner Match 73,Winner Match 74,South Korea,Germany,0,2,10,3,0,away,False
17,90,Round of 16,2,Winner Match 75,Winner Match 76,Netherlands,Brazil,1,2,11,3,0,away,False
18,91,Round of 16,2,Winner Match 77,Winner Match 78,France,Norway,2,1,10,2,0,home,False
19,92,Round of 16,2,Winner Match 79,Winner Match 80,Mexico,England,0,2,10,3,0,away,False
20,93,Round of 16,2,Winner Match 81,Winner Match 82,Türkiye,Belgium,1,2,10,4,0,away,False
21,94,Round of 16,2,Winner Match 83,Winner Match 84,USA,Uruguay,1,2,10,3,0,away,False
22,95,Round of 16,2,Winner Match 85,Winner Match 86,Spain,Switzerland,3,0,12,2,0,home,False
23,96,Round of 16,2,Winner Match 87,Winner Match 88,Portugal,Argentina,1,2,11,3,0,away,False
24,97,Quarter-final,4,Winner Match 89,Winner Match 90,Germany,Brazil,1,2,10,3,0,away,False
25,98,Quarter-final,4,Winner Match 91,Winner Match 92,France,England,2,1,10,3,0,home,False
26,99,Quarter-final,4,Winner Match 93,Winner Match 94,Belgium,Uruguay,1,1,10,3,0,away,True
27,100,Quarter-final,4,Winner Match 95,Winner Match 96,Spain,Argentina,2,1,11,3,0,home,False
28,101,Semi-final,8,Winner Match 97,Winner Match 98,Brazil,France,1,2,10,3,0,away,False
29,102,Semi-final,8,Winner Match 99,Winner Match 100,Uruguay,Spain,0,2,10,2,0,away,False
30,103,Third-place playoff,8,Loser Match 101,Loser Match 102,Brazil,Uruguay,2,1,10,3,0,home,False
31,104,Final,16,Winner Match 101,Winner Match 102,France,Spain,1,2,10,3,0,away,False

In [11]:
# ── FINAL VALIDATION ──────────────────────────────────────────────────────────
ko_cols = ['predicted_home_team','predicted_away_team','predicted_home_goals',
           'predicted_away_goals','corners','yellow_cards','red_cards',
           'match_winner','penalties']

assert len(group_predictions) == 72,    f'Expected 72 group matches, got {len(group_predictions)}'
assert len(knockout_predictions) == 32, f'Expected 32 knockout matches, got {len(knockout_predictions)}'
assert group_predictions[['predicted_home_goals','predicted_away_goals','corners',
                           'yellow_cards','red_cards','winning_team']].isnull().sum().sum() == 0
assert knockout_predictions[ko_cols].isnull().sum().sum() == 0

# Score distribution sanity check
avg_goals = (group_predictions['predicted_home_goals'] + group_predictions['predicted_away_goals']).mean()
avg_corners = group_predictions['corners'].mean()
avg_yellows = group_predictions['yellow_cards'].mean()

print('='*60)
print('✅ ALL PREDICTIONS COMPLETE — NO None VALUES')
print('='*60)
print(f'  Group matches:    72')
print(f'  Knockout matches: 32')
print(f'  Total:            104')
print(f'  Avg goals/match (group): {avg_goals:.2f}  (WC historical: ~2.6)')
print(f'  Avg corners/match:       {avg_corners:.1f}  (historical: ~10)')
print(f'  Avg yellows/match:       {avg_yellows:.1f}  (historical: ~3)')
print()
print('🏆 Predicted Winner: SPAIN')
print('🥈 Runner-up:        France')
print('🥉 Third place:      Brazil')

============================================================
✅ ALL PREDICTIONS COMPLETE — NO None VALUES
============================================================
  Group matches:    72
  Knockout matches: 32
  Total:            104
  Avg goals/match (group): 2.54  (WC historical: ~2.6)
  Avg corners/match:       9.9  (historical: ~10)
  Avg yellows/match:       2.8  (historical: ~3)

🏆 Predicted Winner: SPAIN
🥈 Runner-up:        France
🥉 Third place:      Brazil

In [12]:
# ── EXPORT FINAL PREDICTION TABLES ───────────────────────────────────────────
print('📋 GROUP STAGE PREDICTIONS (sample - first 12 matches):')
display(group_predictions[['match_id','group','home_team','away_team','date',
                            'predicted_home_goals','predicted_away_goals',
                            'corners','yellow_cards','red_cards','winning_team']].head(12))

print('\n📋 KNOCKOUT PREDICTIONS (all 32 matches):')
display(knockout_predictions[['match_id','round','multiplier',
                               'predicted_home_team','predicted_away_team',
                               'predicted_home_goals','predicted_away_goals',
                               'corners','yellow_cards','red_cards',
                               'match_winner','penalties']])

📋 GROUP STAGE PREDICTIONS (sample - first 12 matches):

,match_id,group,home_team,away_team,date,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,winning_team
0,1,A,Mexico,South Africa,2026-06-11,2,0,10,3,0,home
1,2,A,South Korea,Czechia,2026-06-12,1,1,9,3,0,draw
2,3,A,Mexico,South Korea,2026-06-18,2,1,10,3,0,home
3,4,A,Czechia,South Africa,2026-06-18,1,0,9,3,0,home
4,5,A,Mexico,Czechia,2026-06-25,2,1,10,3,0,home
5,6,A,South Africa,South Korea,2026-06-25,1,1,9,3,0,draw
6,7,B,Canada,Bosnia-Herzegovina,2026-06-12,2,0,10,3,0,home
7,8,B,Qatar,Switzerland,2026-06-13,0,2,9,2,0,away
8,9,B,Canada,Qatar,2026-06-18,2,0,10,2,0,home
9,10,B,Switzerland,Bosnia-Herzegovina,2026-06-19,2,0,10,3,0,home
10,11,B,Canada,Switzerland,2026-06-25,1,2,10,3,0,away
11,12,B,Bosnia-Herzegovina,Qatar,2026-06-25,1,1,8,3,1,draw

📋 KNOCKOUT PREDICTIONS (all 32 matches):

,match_id,round,multiplier,predicted_home_team,predicted_away_team,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,match_winner,penalties
0,73,Round of 32,1,South Korea,Canada,1,2,10,3,0,home,False
1,74,Round of 32,1,Germany,Scotland,2,0,10,2,0,home,False
2,75,Round of 32,1,Netherlands,Morocco,1,1,10,3,0,home,False
3,76,Round of 32,1,Brazil,Japan,2,0,11,2,0,home,False
4,77,Round of 32,1,France,Senegal,2,0,10,3,0,home,False
5,78,Round of 32,1,Ecuador,Norway,1,2,10,3,0,away,False
6,79,Round of 32,1,Mexico,Ivory Coast,2,1,10,3,0,home,False
7,80,Round of 32,1,England,Algeria,2,0,10,2,0,home,False
8,81,Round of 32,1,Türkiye,Croatia,1,1,10,4,1,home,True
9,82,Round of 32,1,Belgium,Sweden,2,0,10,3,0,home,False
10,83,Round of 32,1,USA,Australia,2,0,10,2,0,home,False
11,84,Round of 32,1,Egypt,Uruguay,0,2,9,3,0,away,False
12,85,Round of 32,1,Spain,DR Congo,4,0,12,2,0,home,False
13,86,Round of 32,1,Switzerland,Ghana,2,1,10,3,0,home,False
14,87,Round of 32,1,Portugal,Austria,2,1,11,3,0,home,False
15,88,Round of 32,1,Argentina,Colombia,2,1,10,3,0,home,False
16,89,Round of 16,2,South Korea,Germany,0,2,10,3,0,away,False
17,90,Round of 16,2,Netherlands,Brazil,1,2,11,3,0,away,False
18,91,Round of 16,2,France,Norway,2,1,10,2,0,home,False
19,92,Round of 16,2,Mexico,England,0,2,10,3,0,away,False
20,93,Round of 16,2,Türkiye,Belgium,1,2,10,4,0,away,False
21,94,Round of 16,2,USA,Uruguay,1,2,10,3,0,away,False
22,95,Round of 16,2,Spain,Switzerland,3,0,12,2,0,home,False
23,96,Round of 16,2,Portugal,Argentina,1,2,11,3,0,away,False
24,97,Quarter-final,4,Germany,Brazil,1,2,10,3,0,away,False
25,98,Quarter-final,4,France,England,2,1,10,3,0,home,False
26,99,Quarter-final,4,Belgium,Uruguay,1,1,10,3,0,away,True
27,100,Quarter-final,4,Spain,Argentina,2,1,11,3,0,home,False
28,101,Semi-final,8,Brazil,France,1,2,10,3,0,away,False
29,102,Semi-final,8,Uruguay,Spain,0,2,10,2,0,away,False
30,103,Third-place playoff,8,Brazil,Uruguay,2,1,10,3,0,home,False
31,104,Final,16,France,Spain,1,2,10,3,0,away,False